<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="ModbusToDword" Id="{7055a443-257c-4856-94f4-5b16089f6de4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ModbusToDword : DWORD
VAR_INPUT
	wHi : WORD;
    wLo : WORD;
END_VAR
VAR

	 dw : DWORD;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// złożenie 2xWORD -> 32-bit (Big-Endian: HI potem LO)
dw := SHL(WORD_TO_DWORD(wHi), 16) OR WORD_TO_DWORD(wLo);

ModbusToDword := dw;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>