<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_DigitalSensNO" Id="{9b7f398c-5bf7-4085-9c37-3cc19cb2758d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DigitalSensNO
VAR_INPUT
	_input	: BOOL;
END_VAR

VAR_OUTPUT
	_output : BOOL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[_output := _input;]]></ST>
    </Implementation>
    <Property Name="IsActive" Id="{d21f2347-78c6-48ff-b8b4-4796ac7e56b7}">
      <Declaration><![CDATA[PROPERTY IsActive : BOOL]]></Declaration>
      <Get Name="Get" Id="{10566830-eb48-451a-8cea-d902e630293f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsActive:= _output;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_DigitalSensNO">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_DigitalSensNO.IsActive.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>