<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_ContactNO" Id="{30a7062e-ec4c-44b9-8e74-fdb7b9cc06c4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ContactNO
VAR_INPUT
	_input	: BOOL;
END_VAR

VAR_OUTPUT
	_output : BOOL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[_output := _input;]]></ST>
    </Implementation>
    <Property Name="IsActive" Id="{d2c0b225-061e-4b45-8db5-ed99a3e861f1}">
      <Declaration><![CDATA[PROPERTY IsActive : BOOL]]></Declaration>
      <Get Name="Get" Id="{684a908d-1b21-4c62-860a-22b93fc8752b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsActive:= _output;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>