<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_ContactNC" Id="{fb16d159-6fdb-45c0-92e4-67f3693c18f8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ContactNC
VAR_INPUT
	_input	: BOOL;
END_VAR

VAR_OUTPUT
	_output : BOOL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[_output := NOT _input;]]></ST>
    </Implementation>
    <Property Name="IsActive" Id="{7d841797-3b93-45f5-91ea-6e320de1b985}">
      <Declaration><![CDATA[PROPERTY IsActive : BOOL]]></Declaration>
      <Get Name="Get" Id="{6af771e9-ccc6-4d12-a5e7-41cdf42681db}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsActive:= _output;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>