<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="F_Words_to_Real_1" Id="{b65d7323-6a4b-4254-b16f-c286bc1377ef}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Words_to_Real_1 : REAL
VAR_INPUT
	wWord : WORD;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MEMCPY(ADR(F_Words_to_Real_1),ADR(wWord),2);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>