<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="ModbusToReal" Id="{beda0692-9542-4cc6-98a2-158817cecd56}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ModbusToReal : REAL
VAR_INPUT
	wHi : WORD;
    wLo : WORD;
END_VAR
VAR
	
	 dw : DWORD;
	 rR  : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// złożenie 2xWORD -> 32-bit (Big-Endian: HI potem LO)
dw := SHL(WORD_TO_DWORD(wHi), 16) OR WORD_TO_DWORD(wLo);

// reinterpretacja bitów DWORD jako REAL
MEMCPY(ADR(rR), ADR(dw), SIZEOF(rR));

ModbusToReal := rR;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>