<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{1f90028c-37a4-400b-9dcd-f4342dcec394}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

	//Obsługa Modbusa
	fbModbusoperation	 : FB_InvModbusOperation;	

		
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//DewateringProcess();
FermentationProcess();
BiogasProcess();
CogenerationProcess();
FertilizerProcess();

ModbusScheduler();



//Modbus Inverter obsługa wszystkich napedow
fbModbusoperation();		// obsługa napędów Modbus U11-SP01, U71-VR01_M01, U81-VR01_M02, U91-VR01_M03


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>