<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_TermFuse" Id="{48873c51-13d8-447a-830c-602de958a94d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TermFuse
VAR
	_input AT%I* : BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IsActive" Id="{6ff4f648-9752-442a-8a44-1a86a88bd89e}">
      <Declaration><![CDATA[PROPERTY IsActive : BOOL]]></Declaration>
      <Get Name="Get" Id="{9b2478b6-2af5-4f27-adb9-9e26001a1296}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsActive := _input;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>