<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="DewateringProcess" Id="{2dba32da-2625-43de-81be-5f749617ce24}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM DewateringProcess
VAR
	//kontakty z systemu podrzednego- odbierane
	fbContactPraca 		: FB_ContactNO; 
	fbContactAwaria		: FB_ContactNC;
	//kontakty z systemu podrzednego- wysylane
	fbContactStart		: FB_ContactNO;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Action
ACT_Contact();









]]></ST>
    </Implementation>
    <Action Name="ACT_Contact" Id="{43f73a8b-7e3a-4774-900e-e279f9a14622}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">38L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">39L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_input"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">40L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_output"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">41L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_ContactNO"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">42L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbContactStart"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">43L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"19, 12, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">37L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">45L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Dewatering.stDewatering.bStart"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">46L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"2, 14, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">44L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">48L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Dewatering.DO_Start"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">49L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"32, 14, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">47L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">23L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">24L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_input"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_output"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">26L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_ContactNC"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbContactAwaria"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">28L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"19, 2, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">22L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">30L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Dewatering.DI_Awaria"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">31L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 4, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">29L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">33L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Dewatering.stDewatering.bAwaria"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">34L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"32, 4, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">32L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">10L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">12L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_input"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_output"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_ContactNO"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">8L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbContactPraca"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">9L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"19, 7, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">1L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">15L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Dewatering.DI_Praca"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">16L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"5, 9, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">14L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">15L</v>
                      <v n="DestPinId">10L</v>
                      <v n="Id">17L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">19L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Dewatering.stDewatering.bPraca"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">20L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"32, 9, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">18L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">12L</v>
                      <v n="DestPinId">19L</v>
                      <v n="Id">21L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, -9, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">30L</v>
                      <v n="DestPinId">23L</v>
                      <v n="Id">35L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, -9, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">24L</v>
                      <v n="DestPinId">33L</v>
                      <v n="Id">36L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">45L</v>
                      <v n="DestPinId">38L</v>
                      <v n="Id">50L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"-2, -13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">39L</v>
                      <v n="DestPinId">48L</v>
                      <v n="Id">51L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">36L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">27</v>
                        <v n="Y">4</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">27</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">31</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">35L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">17</v>
                        <v n="Y">4</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">17</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">18</v>
                          <v n="Y">4</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">21L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">27</v>
                        <v n="Y">9</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">27</v>
                          <v n="Y">9</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">31</v>
                          <v n="Y">9</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">17L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">17</v>
                        <v n="Y">9</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">17</v>
                          <v n="Y">9</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">18</v>
                          <v n="Y">9</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">51L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">27</v>
                        <v n="Y">14</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">27</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">31</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">50L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">17</v>
                        <v n="Y">14</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">17</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">18</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">48</v>
                <v n="CanvasHeight">15</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
    <LineIds Name="DewateringProcess">
      <LineId Id="3" Count="2" />
      <LineId Id="8" Count="7" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>