<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="EtaHasBit" Id="{170bfd13-bf01-491b-96d8-8ba34effd3c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION EtaHasBit : BOOL
VAR_INPUT
	w		: WORD;
	bBit	: INT;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[EtaHasBit := (w AND SHL(WORD#1, bBit)) <> 0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>