<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FertilizerProcess" Id="{ae9cea5e-de76-4d67-bab9-1dcc1d16bc80}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM FertilizerProcess
VAR
	//Napedy M01 M02 VR01 - schemat U71, U81	
	fbDrvInv_M01 		: FB_DriveInv(7, E_InvType.Schneider);
	fbDrvContrInv_M01   : FB_DriveControl(fbDrvInv_M01);
	
	fbDrvInv_M02 		: FB_DriveInv(8, E_InvType.Schneider);
	fbDrvContrInv_M02   : FB_DriveControl(fbDrvInv_M02);
	
	//Naped klapy M03 VR01 - schemat U91 
	fbDrvInv_M03 		: FB_DriveInv(9, E_InvType.Schneider);
	fbDrvContrInv_M03   : FB_DriveControl(fbDrvInv_M03);
	
	//Naped wentylator BL01
	fbDrv_BL01			: FB_Drive_1C();
	fbDrvContr_BL01		: FB_DriveControl(fbDrv_BL01);

	//Napedy podajnik SC-01 i SC02
	fbDrv_SC01			: FB_Drive_1C();
	fbDrvContr_SC01	    : FB_DriveControl(fbDrv_SC01);
	
	fbDrv_SC02			: FB_Drive_1C();
	fbDrvContr_SC02		: FB_DriveControl(fbDrv_SC02);
		
	//Napedy S01_E01 i S02_E02
	fbDrv_E01			: FB_Drive_1C();
	fbDrvContr_E01	    : FB_DriveControl(fbDrv_E01);
	
	fbDrv_E02			: FB_Drive_1C();
	fbDrvContr_E02		: FB_DriveControl(fbDrv_E02);
	
	//Temp Sensor
	fbTempSens_H01	 	: FB_Scaling; //Czujnik temperatury w reaktorze R01

	(***********************************************Process Controlller****************************************************************************************)

	(************** Flap controller **************************************************)
	//fbFlapControl		 	: FB_FlapCtrl; //controller bloku sterowania klapa
	
    


	bCmdHome   : BOOL;   // z SCADA – start bazowania testowego
	

	

//    bDrvOpen   : BOOL;   // sterowanie falownikiem – otwieranie
//    bDrvClose  : BOOL;   // sterowanie falownikiem – zamykanie
//    bHomeDone  : BOOL;   // flaga: baza złapana

    
	rZ         : R_TRIG; // wykrywanie zbocza na Z
	
	//sterowanie otwarciem klapy
	fbTrigFwd : R_TRIG; //zamykanie
    fbTrigRev : R_TRIG; //otwieranie

    bFwdActive : BOOL;   // napęd pracuje w przód (otwieranie)
    bRevActive : BOOL;   // napęd pracuje w tył (zamykanie)


    // sterowanie stanami klapy
   	eFlapState : E_FlapState := E_FlapState.IdleClosed;

    // impulsów do pełnego otwarcia
    nTargetOpen : DINT := 266;  // 800/3 = ~266 impulsów
    TOL 		: DINT := 3;            // tolerancja pozycji
	
	rOpenFast  : REAL := 5.0;  // Hz – prędkość szybka
    rOpenSlow  : REAL := 3.0;   // Hz – prędkość wolna
    rCloseFast : REAL := 5.0;
    rCloseSlow : REAL := 3.0;
    nDecelImp  : DINT := 80;    // ile impulsów przed celem zwalniamy
	
	nEncHelp	: UINT;	
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Action
ACT_TempSens();
ACT_Motor(); //nastawy z SCADA
ACT_WeightSensor(); //Sensor wagowy
//ACT_Control(); //Sterowanie procesem higienizacji

//**********************************VR01*****************************************************
//M01
//fbDrvContrInv_M01.FreqSetPoint:=10;
//fbDrvContrInv_M01.SetForward:=TRUE;
fbDrvContrInv_M01();
GVL_Fertilizer.stDriveStatus_M01 := fbDrvContrInv_M01.StatusStruct(); //zwróc strukturę
//M02
fbDrvContrInv_M02();
GVL_Fertilizer.stDriveStatus_M02 := fbDrvContrInv_M02.StatusStruct(); //zwróc strukturę
//M03
//fbDrvContrInv_M03();
//GVL_Fertilizer.stDriveStatus_M03 := fbDrvContrInv_M03.StatusStruct();

//**********************************BL01*****************************************************
//BL01
fbDrvContr_BL01();
GVL_Fertilizer.stDriveStatus_BL01 := fbDrvContr_BL01.StatusStruct(); //zwróc strukturę

//**********************************S01 i S02*****************************************************
//SC01
fbDrvContr_SC01();
GVL_Fertilizer.stDriveStatus_SC01 := fbDrvContr_SC01.StatusStruct(); //zwróc strukturę
//SC02
fbDrvContr_SC02();
GVL_Fertilizer.stDriveStatus_SC02 := fbDrvContr_SC02.StatusStruct(); //zwróc strukturę
//E01
fbDrvContr_E01();
GVL_Fertilizer.stDriveStatus_E01 := fbDrvContr_E01.StatusStruct(); //zwróc strukturę
//E02
fbDrvContr_E02();
GVL_Fertilizer.stDriveStatus_E02 := fbDrvContr_E02.StatusStruct(); //zwróc strukturę


nEncHelp := GVL_Fertilizer.nEnc;
// DETEKCJA PRZYCISKÓW SCADA (tylko zbocze)
// Forward  = ZAMYKANIE
// Reverse  = OTWIERANIE
fbTrigFwd(CLK := GVL_Fertilizer.stDriveStatus_M03.bForward);
fbTrigRev(CLK := GVL_Fertilizer.stDriveStatus_M03.bReverse);

//// Start ZAMYKANIA
IF fbTrigFwd.Q THEN
    eFlapState := E_FlapState.Closing;
END_IF;

// Start OTWIERANIA
IF fbTrigRev.Q THEN
    eFlapState := E_FlapState.Opening;
END_IF;

// --- TEST BAZOWANIA ---
// Założenie: klapa jest trochę otwarta, chcemy ją zamknąć aż złapie Z.
rZ(CLK := GVL_Fertilizer.bSenZ);  // detekcja zbocza narastającego Z

// -----------------------------
// 2) Maszyna stanów
// -----------------------------
CASE eFlapState OF

    // ---------------------------------------------
    // 0) Klapa zamknięta, stan spoczynku
    // ---------------------------------------------
    E_FlapState.IdleClosed:

        bFwdActive := FALSE;   // zamykanie OFF
        bRevActive := FALSE;   // otwieranie OFF

        // Jeśli z jakiegoś powodu NIE jesteśmy na Z → dociągamy klapę
        IF NOT GVL_Fertilizer.bSenZ THEN
            eFlapState := E_FlapState.Closing;
        END_IF;
		
		IF GVL_Fertilizer.bSenz AND GVL_Fertilizer.nEnc <> 0 THEN		// 🔥 reset licznika enkodera do 0					
            GVL_Fertilizer.SetCounterValue := 0;
			GVL_Fertilizer.SetCounter := TRUE;
		ELSE
			GVL_Fertilizer.SetCounter := FALSE;
		END_IF


    // ---------------------------------------------
    // 1) OTWIERANIE (Reverse = otwieranie)
    //    szybka faza + wolna faza przed celem
    // ---------------------------------------------
    E_FlapState.Opening:

        bFwdActive := FALSE;
        bRevActive := TRUE;    // REVERSE = otwieranie
		
		GVL_Fertilizer.SetCounter := FALSE;

        // tu możesz wstawić dwie prędkości na falownik,
        // np. przez rSpeedSet wewnątrz fbDrvContrInv_M03:
        
        IF GVL_Fertilizer.nEnc < (nTargetOpen - nDecelImp) THEN
            fbDrvContrInv_M03.FreqSetPoint := rOpenFast;   // szybciej
        ELSE
            fbDrvContrInv_M03.FreqSetPoint := rCloseFast;    // wolniej przy celu
        END_IF
        

        // osiągnięto pozycję otwarcia
        IF GVL_Fertilizer.nEnc >= (nTargetOpen - TOL) THEN

            bRevActive := FALSE;
            eFlapState := E_FlapState.Opened;

            // opcjonalnie "wyciskamy" przycisk OTWÓRZ w SCADA
            GVL_Fertilizer.stDriveStatus_M03.bReverse := FALSE;
        END_IF;


    // ---------------------------------------------
    // 2) Klapa OTWARTA – czekamy na ZAMKNIJ
    // ---------------------------------------------
    E_FlapState.Opened:

        bFwdActive := FALSE;
        bRevActive := FALSE;
        // nic nie robimy – czekamy na zbocze Forward (Closing)


    // ---------------------------------------------
    // 3) ZAMYKANIE (Forward = zamykanie)
    //    szybka faza + wolna faza przed Z
    // ---------------------------------------------
    E_FlapState.Closing:

        bFwdActive := TRUE;     // FORWARD = zamykanie
        bRevActive := FALSE;

        // dwie prędkości przy zamykaniu:
        // daleko od zera szybciej, blisko zera wolno
        
        IF GVL_Fertilizer.nEnc > nDecelImp THEN
            fbDrvContrInv_M03.FreqSetPoint :=rCloseFast;   // szybciej
        ELSE
            fbDrvContrInv_M03.FreqSetPoint := rCloseSlow;    // wolniej przy bazie
        END_IF
        

        // bazowanie na Z – łapiemy ZBROCZE, nie tylko stan
        IF rZ.Q THEN
            bFwdActive := FALSE;
            eFlapState := E_FlapState.IdleClosed;

            // "wyciskamy" przycisk ZAMKNIJ w SCADA
            GVL_Fertilizer.stDriveStatus_M03.bForward := FALSE;
        END_IF;

END_CASE;


// podpięcie do sterownika falownika M03
fbDrvContrInv_M03.SetForward := bFwdActive;  // FORWARD = zamykanie
fbDrvContrInv_M03.SetReverse := bRevActive;  // REVERSE = otwieranie


////M03
fbDrvContrInv_M03();
GVL_Fertilizer.stDriveStatus_M03 := fbDrvContrInv_M03.StatusStruct(); //zwróc strukturę



//nEncHelp := GVL_Fertilizer.nEnc;

//// Obsługa przycisku Forward
//IF fbTrigFwd.Q THEN
//    // Jeśli napęd nie pracuje w przód → włącz przód, wyłącz tył
//    IF NOT bFwdActive THEN
//        bFwdActive := TRUE;
//        bRevActive := FALSE;
//    ELSE
//        // jeśli już pracował w przód, kolejne naciśnięcie zrobi STOP
//        bFwdActive := FALSE;
//    END_IF;

////    // "Wyciskamy" przycisk w SCADA
////    GVL_Fertilizer.stDriveStatus_M03.bForward := FALSE;
//END_IF;

//// Obsługa przycisku Reverse
//IF fbTrigRev.Q THEN
//    // Jeśli napęd nie pracuje w tył → włącz tył, wyłącz przód
//    IF NOT bRevActive THEN
//        bRevActive := TRUE;
//        bFwdActive := FALSE;
//    ELSE
//        // jeśli już pracował w tył, kolejne naciśnięcie zrobi STOP
//        bRevActive := FALSE;
//    END_IF;

////    // "Wyciskamy" przycisk w SCADA
////    GVL_Fertilizer.stDriveStatus_M03.bReverse := FALSE;
//END_IF;

//fbDrvContrInv_M03.SetForward := bFwdActive;
//fbDrvContrInv_M03.SetReverse := bRevActive;


//// --- TEST BAZOWANIA ---
//// Założenie: klapa jest trochę otwarta, chcemy ją zamknąć aż złapie Z.

//rZ(CLK := GVL_Fertilizer.bSenZ);  // detekcja zbocza narastającego Z



//IF rZ.Q THEN
// fbDrvContrInv_M03.SetForward := FALSE;		
// fbDrvContrInv_M03.SetReverse := FALSE;	 
// GVL_Fertilizer.stDriveStatus_M01.bForward := FALSE;
// GVL_Fertilizer.stDriveStatus_M01.bReverse := FALSE;
// // 🔥 reset licznika enkodera do 0
// GVL_Fertilizer.SetCounter      := TRUE;   // impuls na 1 cykl
// GVL_Fertilizer.SetCounterValue := 0;           
//END_IF

//fbDrvContrInv_M03.FreqSetPoint := 3.0;

////M03
//fbDrvContrInv_M03();
//GVL_Fertilizer.stDriveStatus_M03 := fbDrvContrInv_M03.StatusStruct(); //zwróc strukturę
]]></ST>
    </Implementation>
    <Action Name="ACT_Control" Id="{c00a6ec6-8960-40d8-ac4d-33202791525f}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">60L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"266"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">61L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 15, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">59L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">100L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"fbDrvContrInv_M03.SetReverse"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">101L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"58, 15, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">99L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">64L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.bSenZ"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">65L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 16, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">63L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">68L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"false"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">69L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 17, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">67L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">80L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.rPosPV_Percent"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">81L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"54, 7, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">79L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">84L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.bIsOpen"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">85L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"57, 8, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">83L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">76L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.uiPosSP_Percent"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">77L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 13, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">75L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">88L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.bIsClosed"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">89L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"57, 11, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">87L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">92L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.bIsMoving"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">93L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"57, 12, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">91L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">96L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.bFault"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">97L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"57, 14, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">95L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">104L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"fbDrvContrInv_M03.SetForward"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">105L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"58, 16, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">103L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">108L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"fbDrvContrInv_M03.FreqSetPoint"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">109L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"58, 19, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">107L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">116L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.SetCounterValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">117L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"58, 23, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">115L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">72L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.bAuto"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">73L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 5, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">71L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">51L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.bCmdOpen"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">52L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 6, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">50L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">47L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.bCmdClose"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">48L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 7, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">46L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">10L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">12L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">14L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">16L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">18L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">20L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">22L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">24L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">26L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">28L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">30L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">32L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">34L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">36L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">38L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">40L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">42L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">44L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">119L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bAuto"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bCmdOpen"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bCmdClose"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">15L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"uiPosSP_Percent"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">17L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"nEnc"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">19L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"nTargetOpen"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">21L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bHomeSensor"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">23L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bMotorFault"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"rPosPV_Percent"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">27L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bIsOpen"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">29L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bIsClosed"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">31L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bIsMoving"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">33L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bFlapFault"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">35L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bDrvOpen"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">37L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bDrvClose"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">39L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"rFreqSetpoint"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">41L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"bSetCounter"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">43L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"uiSetCounterVal"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">45L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"eState"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">120L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_FlapCtrl"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">8L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbFlapControl"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">9L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"29, 8, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">1L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">51L</v>
                      <v n="DestPinId">12L</v>
                      <v n="Id">53L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">47L</v>
                      <v n="DestPinId">14L</v>
                      <v n="Id">54L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">56L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.nEnc"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">57L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"3, 14, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">55L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">56L</v>
                      <v n="DestPinId">18L</v>
                      <v n="Id">58L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">60L</v>
                      <v n="DestPinId">20L</v>
                      <v n="Id">62L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">64L</v>
                      <v n="DestPinId">22L</v>
                      <v n="Id">66L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">68L</v>
                      <v n="DestPinId">24L</v>
                      <v n="Id">70L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">72L</v>
                      <v n="DestPinId">10L</v>
                      <v n="Id">74L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">76L</v>
                      <v n="DestPinId">16L</v>
                      <v n="Id">78L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">26L</v>
                      <v n="DestPinId">80L</v>
                      <v n="Id">82L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">28L</v>
                      <v n="DestPinId">84L</v>
                      <v n="Id">86L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">30L</v>
                      <v n="DestPinId">88L</v>
                      <v n="Id">90L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">32L</v>
                      <v n="DestPinId">92L</v>
                      <v n="Id">94L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">34L</v>
                      <v n="DestPinId">96L</v>
                      <v n="Id">98L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">36L</v>
                      <v n="DestPinId">100L</v>
                      <v n="Id">102L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">38L</v>
                      <v n="DestPinId">104L</v>
                      <v n="Id">106L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">40L</v>
                      <v n="DestPinId">108L</v>
                      <v n="Id">110L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">112L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.SetCounter"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">113L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"58, 20, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">111L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">42L</v>
                      <v n="DestPinId">112L</v>
                      <v n="Id">114L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">44L</v>
                      <v n="DestPinId">116L</v>
                      <v n="Id">118L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">122L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.stFlapControl.eState"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">123L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"58, 24, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">121L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">119L</v>
                      <v n="DestPinId">122L</v>
                      <v n="Id">124L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">53L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">19</v>
                        <v n="Y">6</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">true</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">19</v>
                          <v n="Y">6</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">6</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">9</v>
                        </o>
                        <o>
                          <v n="X">23</v>
                          <v n="Y">11</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">6</v>
                        </o>
                        <o>
                          <v n="X">28</v>
                          <v n="Y">11</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">124L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">20</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">20</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">100</v>
                        </o>
                        <o>
                          <v n="X">46</v>
                          <v n="Y">20</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">41</v>
                        </o>
                        <o>
                          <v n="X">46</v>
                          <v n="Y">22</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">38</v>
                        </o>
                        <o>
                          <v n="X">50</v>
                          <v n="Y">22</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">41</v>
                        </o>
                        <o>
                          <v n="X">50</v>
                          <v n="Y">24</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">38</v>
                        </o>
                        <o>
                          <v n="X">57</v>
                          <v n="Y">24</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">54L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">19</v>
                        <v n="Y">7</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">true</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">19</v>
                          <v n="Y">7</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">21</v>
                          <v n="Y">7</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">9</v>
                        </o>
                        <o>
                          <v n="X">21</v>
                          <v n="Y">12</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">6</v>
                        </o>
                        <o>
                          <v n="X">28</v>
                          <v n="Y">12</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">70L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">7</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">7</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">28</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">78L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">21</v>
                        <v n="Y">13</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">21</v>
                          <v n="Y">13</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">28</v>
                          <v n="Y">13</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">82L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">10</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">10</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">48</v>
                          <v n="Y">10</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">3</v>
                        </o>
                        <o>
                          <v n="X">48</v>
                          <v n="Y">7</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">12</v>
                        </o>
                        <o>
                          <v n="X">53</v>
                          <v n="Y">7</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">86L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">11</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">11</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">50</v>
                          <v n="Y">11</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">3</v>
                        </o>
                        <o>
                          <v n="X">50</v>
                          <v n="Y">8</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">12</v>
                        </o>
                        <o>
                          <v n="X">56</v>
                          <v n="Y">8</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">74L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">17</v>
                        <v n="Y">5</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">true</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">17</v>
                          <v n="Y">5</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">5</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">9</v>
                        </o>
                        <o>
                          <v n="X">25</v>
                          <v n="Y">10</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">6</v>
                        </o>
                        <o>
                          <v n="X">28</v>
                          <v n="Y">10</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">118L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">19</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">47</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">9</v>
                        </o>
                        <o>
                          <v n="X">47</v>
                          <v n="Y">21</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">6</v>
                        </o>
                        <o>
                          <v n="X">51</v>
                          <v n="Y">21</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">9</v>
                        </o>
                        <o>
                          <v n="X">51</v>
                          <v n="Y">23</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">6</v>
                        </o>
                        <o>
                          <v n="X">57</v>
                          <v n="Y">23</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">90L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">12</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">12</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">51</v>
                          <v n="Y">12</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">3</v>
                        </o>
                        <o>
                          <v n="X">51</v>
                          <v n="Y">11</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">12</v>
                        </o>
                        <o>
                          <v n="X">56</v>
                          <v n="Y">11</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">58L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">12</v>
                        <v n="Y">14</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">12</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">28</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">94L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">13</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">13</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">52</v>
                          <v n="Y">13</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">3</v>
                        </o>
                        <o>
                          <v n="X">52</v>
                          <v n="Y">12</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">12</v>
                        </o>
                        <o>
                          <v n="X">56</v>
                          <v n="Y">12</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">98L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">14</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">56</v>
                          <v n="Y">14</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">102L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">15</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">57</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">106L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">16</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">57</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">66L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">13</v>
                        <v n="Y">16</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">13</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">28</v>
                          <v n="Y">16</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">114L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">49</v>
                          <v n="Y">18</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">9</v>
                        </o>
                        <o>
                          <v n="X">49</v>
                          <v n="Y">20</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">6</v>
                        </o>
                        <o>
                          <v n="X">57</v>
                          <v n="Y">20</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">62L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">7</v>
                        <v n="Y">15</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">7</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">28</v>
                          <v n="Y">15</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">110L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">44</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">44</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">50</v>
                          <v n="Y">17</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">9</v>
                        </o>
                        <o>
                          <v n="X">50</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">6</v>
                        </o>
                        <o>
                          <v n="X">57</v>
                          <v n="Y">19</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">74</v>
                <v n="CanvasHeight">26</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
    <Action Name="ACT_Motor" Id="{157fa111-0c10-4c74-bf66-984a77c8c761}">
      <Implementation>
        <ST><![CDATA[
//***********Naped ustawienia VR01************************
//nastawy z SCADA M01
fbDrvContrInv_M01.SetForward	:=GVL_Fertilizer.stDriveStatus_M01.bForward;
fbDrvContrInv_M01.SetReverse	:=GVL_Fertilizer.stDriveStatus_M01.bReverse;
fbDrvContrInv_M01.FreqSetPoint	:=GVL_Fertilizer.stDriveStatus_M01.FrequencySet;

//nastawy z SCADA M02
fbDrvContrInv_M02.SetForward	:=GVL_Fertilizer.stDriveStatus_M02.bForward;
fbDrvContrInv_M02.SetReverse	:=GVL_Fertilizer.stDriveStatus_M02.bReverse;
fbDrvContrInv_M02.FreqSetPoint	:=GVL_Fertilizer.stDriveStatus_M02.FrequencySet;

//nastawy z SCADA M03
//fbDrvContrInv_M03.SetForward	:=GVL_Fertilizer.stDriveStatus_M03.bForward;
//fbDrvContrInv_M03.SetReverse	:=GVL_Fertilizer.stDriveStatus_M03.bReverse;
//fbDrvContrInv_M03.FreqSetPoint  :=GVL_Fertilizer.stDriveStatus_M03.FrequencySet;


//***********Naped ustawienia BL01 ************************
//nastawy z SCADA SC01
fbDrvContr_BL01.SetForward	:=GVL_Fertilizer.stDriveStatus_BL01.bForward;


//***********Naped ustawienia S01 i S02************************
//nastawy z SCADA SC01
fbDrvContr_SC01.SetForward	:=GVL_Fertilizer.stDriveStatus_SC01.bForward;
//nastawy z SCADA SC02
fbDrvContr_SC02.SetForward	:=GVL_Fertilizer.stDriveStatus_SC02.bForward;
//nastawy z SCADA E01
fbDrvContr_E01.SetForward	:=GVL_Fertilizer.stDriveStatus_E01.bForward;
//nastawy z SCADA E02
fbDrvContr_E02.SetForward	:=GVL_Fertilizer.stDriveStatus_E02.bForward;
]]></ST>
      </Implementation>
    </Action>
    <Action Name="ACT_TempSens" Id="{e5be406b-b6a0-4f64-8c1c-50c0deca9433}">
      <Implementation>
        <CFC>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="CFCImplementationObject">
                <o n="Items" t="CFCItemList">
                  <l2 n="InnerList">
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">35L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"0"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">36L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"11, 25, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">34L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">39L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"32767"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">40L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"11, 26, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">38L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">43L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"-50"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">44L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"11, 27, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">42L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">47L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"200"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">48L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"11, 28, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">46L</v>
                    </o>
                    <o t="CFCBoxElement">
                      <o n="Inputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCInputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">10L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">12L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">14L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">16L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="IsExtensiblePin">false</v>
                            <v n="ProcessValue">""</v>
                            <v n="Access" t="ProcessValueAccess">None</v>
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">18L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Outputs" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCOutputPin">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">20L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">22L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Negated">false</v>
                            <v n="SetReset" t="SetReset">None</v>
                            <v n="SetResetRef" t="SetResetRef">None</v>
                            <v n="PretendsToBeConnected">false</v>
                            <v n="Id">24L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Texts" t="CFCItemList">
                        <l2 n="InnerList" cet="CFCText">
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rX"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">11L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">13L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rXmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">15L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmin"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">17L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rYmax"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">19L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmHi"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">21L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_bAlarmLo"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">23L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"_rY"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">25L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"FB_Scaling"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">8L</v>
                          </o>
                          <o>
                            <v n="Bounds">"0, 0, 0, 0"</v>
                            <n n="ElementGroupId" />
                            <v n="Text">"fbTempSens_H01"</v>
                            <v n="Modifiable">true</v>
                            <v n="Id">9L</v>
                          </o>
                        </l2>
                      </o>
                      <o n="Parameters" t="CFCItemList">
                        <l2 n="InnerList" />
                      </o>
                      <n n="PreparedParameters" />
                      <v n="PageArea">0</v>
                      <v n="Bounds">"35, 22, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="EnEno">false</v>
                      <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                      <v n="ContainsExtensibleInputs">false</v>
                      <v n="Forced">false</v>
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">1L</v>
                    </o>
                    <o t="CFCInputElement">
                      <o n="Output" t="CFCOutputPin">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">27L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.TempSens_H01.iRawValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">28L</v>
                      </o>
                      <v n="PageArea">3</v>
                      <v n="Bounds">"11, 24, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">26L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">27L</v>
                      <v n="DestPinId">10L</v>
                      <v n="Id">29L</v>
                    </o>
                    <o t="CFCOutputElement">
                      <o n="Input" t="CFCInputPinWithSetReset">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="ProcessValue">""</v>
                        <v n="Access" t="ProcessValueAccess">None</v>
                        <v n="Negated">false</v>
                        <v n="SetReset" t="SetReset">None</v>
                        <v n="SetResetRef" t="SetResetRef">None</v>
                        <v n="PretendsToBeConnected">false</v>
                        <v n="Id">31L</v>
                      </o>
                      <o n="Text" t="CFCText">
                        <v n="Bounds">"0, 0, 0, 0"</v>
                        <n n="ElementGroupId" />
                        <v n="Text">"GVL_Fertilizer.TempSens_H01.rValue"</v>
                        <v n="Modifiable">true</v>
                        <v n="Id">32L</v>
                      </o>
                      <v n="PageArea">4</v>
                      <v n="Bounds">"54, 26, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="OwningPageId">-1L</v>
                      <v n="Id">30L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">24L</v>
                      <v n="DestPinId">31L</v>
                      <v n="Id">33L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">35L</v>
                      <v n="DestPinId">12L</v>
                      <v n="Id">37L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">39L</v>
                      <v n="DestPinId">14L</v>
                      <v n="Id">41L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">43L</v>
                      <v n="DestPinId">16L</v>
                      <v n="Id">45L</v>
                    </o>
                    <o t="CFCConnection">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="SourcePinId">47L</v>
                      <v n="DestPinId">18L</v>
                      <v n="Id">49L</v>
                    </o>
                  </l2>
                </o>
                <n n="ParameterInitializationMethodGenerator" />
                <o n="RoutingPathTable" t="CFCRoutingPathTable">
                  <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                    <o>
                      <v n="ConnectionId">29L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">28</v>
                        <v n="Y">24</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">28</v>
                          <v n="Y">24</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">34</v>
                          <v n="Y">24</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">33L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">45</v>
                        <v n="Y">26</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">45</v>
                          <v n="Y">26</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">53</v>
                          <v n="Y">26</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">37L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">14</v>
                        <v n="Y">25</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">14</v>
                          <v n="Y">25</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">34</v>
                          <v n="Y">25</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">41L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">16</v>
                        <v n="Y">26</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">16</v>
                          <v n="Y">26</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">34</v>
                          <v n="Y">26</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">45L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">15</v>
                        <v n="Y">27</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">15</v>
                          <v n="Y">27</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">34</v>
                          <v n="Y">27</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                    <o>
                      <v n="ConnectionId">49L</v>
                      <o n="StartPoint" t="CFCPoint">
                        <v n="X">15</v>
                        <v n="Y">28</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">0</v>
                      </o>
                      <v n="Unroutable">false</v>
                      <n n="CorrespondingPageId" />
                      <v n="Locked">false</v>
                    </o>
                    <o>
                      <l2 n="InnerList" cet="CFCPoint">
                        <o>
                          <v n="X">15</v>
                          <v n="Y">28</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">68</v>
                        </o>
                        <o>
                          <v n="X">34</v>
                          <v n="Y">28</v>
                          <v n="IsJoint">false</v>
                          <v n="Flags">97</v>
                        </o>
                      </l2>
                    </o>
                  </d2>
                </o>
                <v n="AutoSizeCanvas">true</v>
                <v n="CanvasWidth">69</v>
                <v n="CanvasHeight">29</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
              <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
              <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
              <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
              <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
              <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
              <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
              <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
              <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
              <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
              <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
              <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
              <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
              <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
              <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
              <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
              <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </CFC>
      </Implementation>
    </Action>
    <Action Name="ACT_WeightSensor" Id="{c3ec4534-bc74-4a01-b06c-42e2c4179453}">
      <Implementation>
        <ST><![CDATA[//******************************************** Weight 01 ****************************************************
// WORD jest ze znakiem więc najpierw konwertujemy na INt aby otrzymac znak a potem na REAL

GVL_Fertilizer.WeightSens_VR01.rWeightValue := TO_REAL(TO_INT(GVL_Fertilizer.WeightSens_VR01.rRawWeightValue));]]></ST>
      </Implementation>
    </Action>
  </POU>
</TcPlcObject>